/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menu;

import Clases.EnlaceBd;
import Registros.JAuditoria;
import Registros.JUregistro;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author pcpublic class Mprincipal extends javax.swing.JFrame implements Runnable{
 */
public class JMenuResponsive extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form JMenuResponsive
     */
    public JMenuResponsive() {
        initComponents();
    
                initComponents();
    
    
      // con = conexion.getConnection();  
         Calendar Fecha = new GregorianCalendar();
         FechaAdmin.setCalendar(Fecha);
         h1= new Thread(this);
         h1.start();
     
 //informacion();
 String fecha = new SimpleDateFormat("dd/MM/yyyy").format(FechaAdmin.getDate());
 String fecha2 = new SimpleDateFormat("dd/MM/yyyy").format(FechaAdmin.getDate());
 String [] dateParts= fecha.split("/");
 String an = dateParts[0];
 String mes = dateParts[1];
 String dia = dateParts[2];
 fecha2 = (an+"/"+mes+"/"+dia);

 FechaAc.setText(fecha2);
 FechaAdmin.setVisible(false);
 IDUSER.setVisible(false);
 
        
        
        
        
        
        
        
        
        
        
        
  //  JDesktopMenu.setVisible(false);
   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        Layout = new javax.swing.JPanel();
        PanelInicio = new org.edisoncor.gui.panel.PanelImage();
        FechaAc = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel95 = new javax.swing.JLabel();
        JLabelNombre = new javax.swing.JLabel();
        IDUSER = new javax.swing.JLabel();
        jLabel98 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Txtinfo = new javax.swing.JTextArea();
        FechaAdmin = new com.toedter.calendar.JDateChooser();
        jLabel104 = new javax.swing.JLabel();
        BtnMensaje = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel107 = new javax.swing.JLabel();
        jLabel106 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        Txtentrada = new javax.swing.JTextField();
        TxtUser = new javax.swing.JTextField();
        TxtRol = new javax.swing.JTextField();
        FechaAc1 = new javax.swing.JLabel();
        jLabel102 = new javax.swing.JLabel();
        clockFace1 = new org.edisoncor.gui.varios.ClockFace();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2000, 1800));
        setMinimumSize(new java.awt.Dimension(1300, 700));

        PanelInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/368940.jpg"))); // NOI18N
        PanelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FechaAc.setBackground(new java.awt.Color(0, 0, 0));
        FechaAc.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        FechaAc.setForeground(new java.awt.Color(255, 255, 255));
        FechaAc.setText("Fecha");
        PanelInicio.add(FechaAc, new org.netbeans.lib.awtextra.AbsoluteConstraints(908, 10, -1, -1));

        Time.setBackground(new java.awt.Color(0, 0, 0));
        Time.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        Time.setForeground(new java.awt.Color(255, 255, 255));
        Time.setText("Hora");
        PanelInicio.add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 10, -1, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel95.setBackground(new java.awt.Color(0, 0, 0));
        jLabel95.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel95.setText("Buenos dias");
        jLabel95.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel95MouseClicked(evt);
            }
        });
        jPanel7.add(jLabel95, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 50));

        JLabelNombre.setBackground(new java.awt.Color(0, 0, 0));
        JLabelNombre.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        JLabelNombre.setText("Nombre");
        JLabelNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel7.add(JLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, 50));

        IDUSER.setBackground(new java.awt.Color(0, 0, 0));
        IDUSER.setFont(new java.awt.Font("Lucida Calligraphy", 1, 14)); // NOI18N
        IDUSER.setText("ID");
        jPanel7.add(IDUSER, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, 50));

        jLabel98.setBackground(new java.awt.Color(0, 0, 0));
        jLabel98.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel98.setText("Ultima Entrada:");
        jPanel7.add(jLabel98, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, 50));

        Txtinfo.setEditable(false);
        Txtinfo.setColumns(20);
        Txtinfo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Txtinfo.setRows(5);
        Txtinfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Mensaje Administrativo"));
        jScrollPane1.setViewportView(Txtinfo);

        jPanel7.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 390, 140));

        FechaAdmin.setBackground(new java.awt.Color(255, 255, 255));
        FechaAdmin.setToolTipText("");
        FechaAdmin.setEnabled(false);
        FechaAdmin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel7.add(FechaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, 110, 30));

        jLabel104.setBackground(new java.awt.Color(0, 0, 0));
        jLabel104.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel104.setText("Rol");
        jPanel7.add(jLabel104, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 100, 50));

        BtnMensaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImgBotones/modificar.png"))); // NOI18N
        BtnMensaje.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        BtnMensaje.setBorderPainted(false);
        BtnMensaje.setContentAreaFilled(false);
        BtnMensaje.setEnabled(false);
        BtnMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMensajeActionPerformed(evt);
            }
        });
        jPanel7.add(BtnMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 120, 40));

        jPanel6.setBackground(new java.awt.Color(0, 51, 102));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel107.setBackground(new java.awt.Color(0, 0, 0));
        jLabel107.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jLabel107.setForeground(new java.awt.Color(255, 255, 255));
        jLabel107.setText("D A T O S    D E    U S U A R I O");
        jPanel6.add(jLabel107, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, -10, 210, 50));

        jPanel7.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 30));

        jLabel106.setBackground(new java.awt.Color(0, 0, 0));
        jLabel106.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel106.setText("Usuario:");
        jPanel7.add(jLabel106, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 100, 50));

        jLabel122.setBackground(new java.awt.Color(0, 0, 0));
        jLabel122.setFont(new java.awt.Font("Agency FB", 0, 18)); // NOI18N
        jLabel122.setForeground(new java.awt.Color(255, 255, 255));
        jLabel122.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoPag.png"))); // NOI18N
        jPanel7.add(jLabel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 130, 130));

        Txtentrada.setEditable(false);
        jPanel7.add(Txtentrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 230, 30));

        TxtUser.setEditable(false);
        jPanel7.add(TxtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 230, 30));

        TxtRol.setEditable(false);
        jPanel7.add(TxtRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 230, 30));

        PanelInicio.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 117, -1, -1));

        FechaAc1.setBackground(new java.awt.Color(0, 0, 0));
        FechaAc1.setFont(new java.awt.Font("Agency FB", 1, 100)); // NOI18N
        FechaAc1.setForeground(new java.awt.Color(255, 255, 255));
        FechaAc1.setText("¡BIENVENIDO!");
        PanelInicio.add(FechaAc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 586, -1, -1));

        jLabel102.setBackground(new java.awt.Color(0, 0, 0));
        jLabel102.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel102.setForeground(new java.awt.Color(255, 255, 255));
        jLabel102.setText("AM");
        PanelInicio.add(jLabel102, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 2, 60, 60));
        PanelInicio.add(clockFace1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 90, -1, -1));

        javax.swing.GroupLayout LayoutLayout = new javax.swing.GroupLayout(Layout);
        Layout.setLayout(LayoutLayout);
        LayoutLayout.setHorizontalGroup(
            LayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutLayout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(PanelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
        );
        LayoutLayout.setVerticalGroup(
            LayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LayoutLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(PanelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jMenu1.setText("|  INICIO  |");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("REGISTROS  |");
        jMenuBar1.add(jMenu2);

        jMenu4.setText("PROCESOS  |");

        jMenuItem1.setText("Asignar PCP");
        jMenu4.add(jMenuItem1);

        jMenuItem2.setText("Laboratorio");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("CONSULTAS & REPORTES  |");
        jMenuBar1.add(jMenu5);

        jMenu6.setText("CONFIGURACIÓN  |");
        jMenuBar1.add(jMenu6);

        jMenu7.setText("SEGURIDAD  |");
        jMenuBar1.add(jMenu7);

        jMenu8.setText("SERVICIOS  | ");
        jMenuBar1.add(jMenu8);

        jMenu9.setText("HERRAMIENTAS  |");
        jMenuBar1.add(jMenu9);

        jMenu10.setText("AYUDA  |");
        jMenuBar1.add(jMenu10);

        jMenu11.setText("CERRAR SESIÓN  |");
        jMenuBar1.add(jMenu11);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(Layout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Layout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
       




        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked

    //JDesktopMenu.setVisible(false);
    PanelInicio.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
          


    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jLabel95MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel95MouseClicked
       // TODO add your handling code here:
    }//GEN-LAST:event_jLabel95MouseClicked

    private void BtnMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMensajeActionPerformed
      
          Connection con;
   EnlaceBd cn = new EnlaceBd();
   PreparedStatement ps;
   ResultSet rs;

        try {
            String sql = "update tableinfo set mensaje=? " ;
            con = cn.getConnection();
            ps = con.prepareStatement(sql);
            ps.setString(1, Txtinfo.getText());
            int res = ps.executeUpdate();

            if (res >= 1) {
                JOptionPane.showMessageDialog(null, " Mensaje Actualizado ", "Mensaje", 1);
            } else {
                JOptionPane.showMessageDialog(null, "Fallo al actualizar los datos....");
            }
        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_BtnMensajeActionPerformed

   
    
    
    
    public void hidemenu() {
    jPanel7.setVisible(false);
    FechaAc1.setVisible(false);
    FechaAc.setVisible(false);
    Time.setVisible(false);
    jLabel102.setVisible(false);
    }
    
    
    
    
    /**
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JMenuResponsive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JMenuResponsive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JMenuResponsive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JMenuResponsive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JMenuResponsive().setVisible(true);
            }
        });
    }
  String hora, minutos, segundos, ampm;
   Thread h1;
       
    
            public void hora()
{
    
  Calendar calendario = new GregorianCalendar();
  Date horaactual= new Date();
  calendario.setTime(horaactual);
  
  hora= calendario.get(Calendar.HOUR_OF_DAY)>9? ""+calendario.get(Calendar.HOUR_OF_DAY):"0"+calendario.get(Calendar.HOUR_OF_DAY);
  minutos= calendario.get(Calendar.MINUTE)>9? ""+calendario.get(Calendar.MINUTE):"0"+calendario.get(Calendar.MINUTE);
  segundos= calendario.get(Calendar.SECOND)>9? ""+calendario.get(Calendar.SECOND):"0"+calendario.get(Calendar.SECOND);

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BtnMensaje;
    private javax.swing.JLabel FechaAc;
    private javax.swing.JLabel FechaAc1;
    public com.toedter.calendar.JDateChooser FechaAdmin;
    public javax.swing.JLabel IDUSER;
    public javax.swing.JLabel JLabelNombre;
    private javax.swing.JPanel Layout;
    private org.edisoncor.gui.panel.PanelImage PanelInicio;
    public javax.swing.JLabel Time;
    public javax.swing.JTextField TxtRol;
    public javax.swing.JTextField TxtUser;
    public javax.swing.JTextField Txtentrada;
    public javax.swing.JTextArea Txtinfo;
    private org.edisoncor.gui.varios.ClockFace clockFace1;
    public javax.swing.JLabel jLabel102;
    public javax.swing.JLabel jLabel104;
    public javax.swing.JLabel jLabel106;
    public javax.swing.JLabel jLabel107;
    private javax.swing.JLabel jLabel122;
    public javax.swing.JLabel jLabel95;
    public javax.swing.JLabel jLabel98;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
               Thread current = Thread.currentThread();


while(current==h1)
{
hora();
Time.setText(hora + ":"+ minutos+":"+segundos);

 int hour = (Integer.parseInt(hora));

if(hour<12){jLabel95.setText("Buenos dias");   jLabel102.setText("AM");}

else if(hour>=12 && hour <19){jLabel95.setText("Buenas tardes");  jLabel102.setText("PM");}

else if(hour>20){jLabel95.setText("Buenas noches"); jLabel102.setText("PM");}


try
{
Thread.sleep(1000);
}

catch(Exception e){}

}
    }
}

