package Menu;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pc
 */
public class Prueba extends javax.swing.JInternalFrame {

    /**
     * Creates new form Prueba
     */
    public Prueba() {
        initComponents();
         ((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
        jPanel2 = new javax.swing.JPanel();
        FechaAc = new javax.swing.JLabel();
        Time = new javax.swing.JLabel();

        setBorder(null);
        setMinimumSize(new java.awt.Dimension(1300, 700));
        setPreferredSize(new java.awt.Dimension(1300, 700));

        jPanel1.setMinimumSize(new java.awt.Dimension(1300, 700));
        jPanel1.setLayout(new java.awt.GridLayout());

        panelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/368940.jpg"))); // NOI18N
        panelImage1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelImage1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 420, 530));

        FechaAc.setBackground(new java.awt.Color(0, 0, 0));
        FechaAc.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        FechaAc.setForeground(new java.awt.Color(255, 255, 255));
        FechaAc.setText("Fecha");
        panelImage1.add(FechaAc, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, -1, -1));

        Time.setBackground(new java.awt.Color(0, 0, 0));
        Time.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        Time.setForeground(new java.awt.Color(255, 255, 255));
        Time.setText("Hora");
        panelImage1.add(Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 10, -1, -1));

        jPanel1.add(panelImage1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FechaAc;
    public javax.swing.JLabel Time;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.edisoncor.gui.panel.PanelImage panelImage1;
    // End of variables declaration//GEN-END:variables
}
